### ISSUE TITLE
Inter-subunit crosslinking data

### ISSUE THREAD

**Issue by Samuel-gwb** [lhatsk/AlphaLink#19]
Hi, great work !
I am wondering if it is possible to leverage intermolecular crosslinking data as distance restraint in alphalink? 
Further, would it be possible to use ambiguous distance restraints, like in NMR structure calculation and haddock, generated from homo-oligomer crosslinking data ? Or translate pair representation / MSA coevolution information into explicit distance restraint ?

**Comment by lhatsk** [comment]
[AlphaLink2](https://github.com/Rappsilber-Laboratory/AlphaLink2) extends AlphaLink to multimers. Note that we focused on heteromeric targets because homomeric targets pose a different problem. Nevertheless, you can also use homomeric crosslinks. The distogram network in AlphaLink allows encoding ambiguity (for example for NMR NOE distance restraints), but we haven't released the distogram model for AlphaLink2 yet (no date atm). For ambiguous homomeric crosslinks, it often works to include both inter- and intra-protein crosslinks and not handle the ambiguity explicitly.

> Or translate pair representation / MSA coevolution information into explicit distance restraint ?

We have a photoAA network that is trained on 10A CA-CA crosslinks which is reasonably close to contacts from co-evolutionary information. You could include these contacts just as photoAA crosslinks.

**Comment by Samuel-gwb** [comment]
Great, many thanks !
